# Site settings
title: "J&J TORRES CONSULTING AS"
email: jdt_joel@yahoo.com
url: http://jjtorresconsulting.no
description: "Your caring janitor"
keywords: "renovations, repairs, paining, gardening, cleaning"
skills: "Renovations & repairs. Painting. Gardening. Cleaning."
meta_author: Torres J&J

# Google webmaster tools
google_verify:

# https://ssl.bing.com/webmaster/configure/verify/ownership Option 2 content= goes here
bing_verify:

# Contact form:
# - static : pass through formspree.io to validate email sending
# - disqus : replace contact form by disqus thread
# - comment the line below if you want to stick with the default PHP contact form
contact: static

# If you use disqus you need disqus shortname
# https://help.disqus.com/customer/portal/articles/466208
disqus_shortname: myshortname

# Color settings (hex-codes without the leading hash-tag)
color:
  primary: 3384f1 #80B3FF
  primary-rgb: "20.52.95" #"128,179,255"
  secondary: f99243
  secondary-dark: 3384f1

# Footer settings
footer:
  copyright: "J&J TORRES CONSULTING AS"
  location: "Oslo og omegn"
  social: "Sosialt nettverk"
  credits: "Takk"

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: twitter
    url: 
  - title: facebook
    url:

# Postal address (add as many lines as necessary)
address:
  - line: Gislestubben 8
  - line: 2040 KLØFTA

# Credits content
credits: 'GitHub, Jekyll & Freelancer theme.'

# Build settings
markdown: kramdown
permalink: pretty
